# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Neptun code check
      uses: bmeaut/ahk-action-neptuncheck@v1

    - name: Build with dotnet
      run: dotnet build Feladatok/Signals.csproj

    # - name: Build and publish with dotnet
    #   run: dotnet publish Feladatok/Signals.csproj -o Feladatok/bin/publish    
      
    #- name: Upload executable artifact
    #  uses: actions/upload-artifact@v1.0.0
    #  with: 
    #    name: Executable
    #    path: Feladatok/bin/Debug/netcoreapp3.1/publish
